[profile.default]
src = 'contracts'
solc_version = "0.8.23"
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200
remappings = [
    '@superfluid-finance/ethereum-contracts/contracts/=../ethereum-contracts/contracts/',
    '@superfluid-finance/solidity-semantic-money/src/=../solidity-semantic-money/src/',
    '@openzeppelin/=../../node_modules/@openzeppelin/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    '@perimetersec/=lib/',
    'forge-std/=../../lib/forge-std/src/']
out = 'build/foundry/out'
allow_paths=["../../", "../../packages/ethereum-contracts"]
libs = ["node_modules", "lib"]
